---

- name: install basic apt packages
  apt: >
    pkg={{ item }} 
    state=present
  with_items:
    - curl
    - git
    - python-pip
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-dev
