---
# Nginx
test_vhosts_nossl:
  - listen: "80"
    server_name: "localhost _"
    root: "{{ frontend_path }}/build"
    index: "index.html index.htm"

test_upstreams:
  - name: test_backend
    strategy: "least_conn"
    servers:
      - "localhost:5000 max_fails=3 fail_timeout=30s"
